spring.application.name=analiseriscofraude

# # Endereço do cluster Kafka
# spring.kafka.bootstrap-servers=localhost:9092

# # Configuração do Consumidor
# spring.kafka.consumer.group-id=inventario-group
# spring.kafka.consumer.auto-offset-reset=earliest

# # Como deserializar a chave e o valor da mensagem (Texto puro neste caso)
# spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
# spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.JSONDeserializer

# Configuração do Ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3
spring.ai.ollama.chat.options.temperature=0.0

# Configuração do banco H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa

# Configurar envio de e-mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=seupedidoaprovado@gmail.com
# ⚠️ Não é a sua senha normal! É a "Senha de App" gerada na segurança da conta Google
spring.mail.password=abcd-efgh-ijkl-mnop 

# Configurações de segurança obrigatórias
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true